use master

create database  proyectotablajugadores

select * from proyectotablajugadores.futbolistas 


-- select para probar como se veia la vista en jugadores  Estos script hay que ponerlo en la clase Repo


-- jugadores
select f.nombre_futbolista, f.apellido_futbolista, f.goles, f.asistencias , f.tarj_amarillas , f.tarj_rojas , f.partidos, f.edad, pp.nombre_puesto as puesto, e.nombre_equipo, p.nombre_pais , sp.nombre_segundo_pais  from proyectotablajugadores.futbolistas f left join equipos e on e.id_equipo = f.id_equipo 
left join paises p on p.id_pais = f.id_pais 
left join segundo_pais sp on sp.id_segundo_pais = f.id_segundo_pais 
left join proyectotablajugadores.puesto pp on f.id_puesto = pp.id_puesto 

-- arqueros 

select f.nombre_futbolista, f.apellido_futbolista, f.edad, f.total_atajadas , f.partidos, ROUND(f.total_atajadas / f.partidos, 2)  as Tapadas_Partido, f.porteria_a_cero , round(f.porteria_a_cero /f.partidos,1 ) as Porteria_A_Cero_Por_Cotejo, f.goles_en_contra , round(f.goles_en_contra / f.partidos , 1) as Goles_Encajados_Partido, f.penales_tapados , e.nombre_equipo, p.nombre_pais , sp.nombre_segundo_pais  from proyectotablajugadores.futbolistas f left join equipos e on e.id_equipo = f.id_equipo 
left join paises p on p.id_pais = f.id_pais 
left join segundo_pais sp on sp.id_segundo_pais = f.id_segundo_pais 
left join proyectotablajugadores.puesto pp on f.id_puesto = pp.id_puesto 
where pp.nombre_puesto  = 'Arquero'
order  by f.porteria_a_cero 

-- Goleadores
select f.nombre_futbolista, f.apellido_futbolista, f.goles, f.partidos, f.edad, f.puesto, e.nombre_equipo, p.nombre_pais , sp.nombre_segundo_pais  from proyectotablajugadores.futbolistas f left join equipos e on e.id_equipo = f.id_equipo 
left join paises p on p.id_pais = f.id_pais 
left join segundo_pais sp on sp.id_segundo_pais = f.id_segundo_pais 
WHERE f.goles > 0 ORDER BY f.goles desc

-- Asistidores
select f.nombre_futbolista, f.apellido_futbolista, f.asistencias , f.partidos, f.edad, f.puesto, e.nombre_equipo, p.nombre_pais , sp.nombre_segundo_pais  from proyectotablajugadores.futbolistas f left join equipos e on e.id_equipo = f.id_equipo 
left join paises p on p.id_pais = f.id_pais 
left join segundo_pais sp on sp.id_segundo_pais = f.id_segundo_pais 
WHERE f.asistencias  > 0 ORDER BY f.asistencias  desc


-- Amonestados
select f.nombre_futbolista, f.apellido_futbolista, f.puesto , f.tarj_amarillas, f.tarj_rojas, (f.tarj_amarillas + f.tarj_rojas ) as Total_Tarjetas, f.partidos, f.edad, e.nombre_equipo, p.nombre_pais , sp.nombre_segundo_pais  from proyectotablajugadores.futbolistas f left join equipos e on e.id_equipo = f.id_equipo 
left join paises p on p.id_pais = f.id_pais 
left join segundo_pais sp on sp.id_segundo_pais = f.id_segundo_pais 
WHERE f.tarj_amarillas  > 0 or f.tarj_rojas  > 0 ORDER BY total_tarjetas desc

------------------------------------------------------------------------------------
-- inserts que se agrega en mysql

-- Los puestos se agregan en mysql 

Insert into proyectotablajugadores.puesto values
(0, 'Arquero'),
(0, 'Lateral Derecho'),
(0, 'Defensa Central'),
(0, 'Lateral Izquierdo'),
(0, 'Volante Defensivo'),
(0, 'Volante Derecho'),
(0, 'Volante Central'),
(0, 'Volante Izquierdo'),
(0, 'Volante Ofensivo'),
(0, 'Extremo Derecho'),
(0, 'Extremo Izquierdo'),
(0, 'Delantero')

-- equipos 
INSERT INTO proyectotablajugadores.equipos  values
(0, 'ADT'),
(0, 'Alianza Atlético'),
(0, 'Alianza Lima'),
(0, 'Alianza Universidad'),
(0, 'Atlético Grau'),
(0, 'Ayacucho FC'),
(0,'Cienciano'),
(0,'Comerciantes Unidos'),
(0, 'Cusco FC'),
(0, 'Deportivo Garcilaso'),
(0, 'FBC Melgar'),
(0, 'Juan Pablo II College'),
(0, 'Los Chankas'),
(0, 'Sport Boys'),
(0,'Sport Huancayo'),
(0,'Sporting Cristal'),
(0, 'Universitario'),
(0, 'UTC');

-- pais y segundo pais se agrega lo mismo, solo es cambiar el nombre en cada tabla
INSERT INTO proyectotablajugadores.paises   (codigo_pais, nombre_pais) values
('00', 'Ninguno'),
('AF', 'Afganistán'),
('AL', 'Albania'),
('DZ', 'Argelia'),
('AS', 'Samoa Americana'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguila'),
('AQ', 'Antártida'),
('AG', 'Antigua y Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaiyán'),
('BS', 'Bahamas'),
('BH', 'Baréin'),
('BD', 'Bangladés'),
('BB', 'Barbados'),
('BY', 'Bielorrusia'),
('BE', 'Bélgica'),
('BZ', 'Belice'),
('BJ', 'Benín'),
('BM', 'Bermudas'),
('BT', 'Bután'),
('BO', 'Bolivia'),
('BA', 'Bosnia y Herzegovina'),
('BW', 'Botsuana'),
('BV', 'Isla Bouvet'),
('BR', 'Brasil'),
('IO', 'Territorio Británico del Océano Índico'),
('BN', 'Brunéi'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Camboya'),
('CM', 'Camerún'),
('CA', 'Canadá'),
('CV', 'Cabo Verde'),
('KY', 'Islas Caimán'),
('CF', 'República Centroafricana'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Isla de Navidad'),
('CC', 'Islas Cocos'),
('CO', 'Colombia'),
('KM', 'Comoras'),
('CG', 'República del Congo'),
('CD', 'República Democrática del Congo'),
('CK', 'Islas Cook'),
('CR', 'Costa Rica'),
('CI', 'Costa de Marfil'),
('HR', 'Croacia'),
('CU', 'Cuba'),
('CW', 'Curazao'),
('CY', 'Chipre'),
('CZ', 'República Checa'),
('DK', 'Dinamarca'),
('DJ', 'Yibuti'),
('DM', 'Dominica'),
('DO', 'República Dominicana'),
('EC', 'Ecuador'),
('EG', 'Egipto'),
('SV', 'El Salvador'),
('GQ', 'Guinea Ecuatorial'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Etiopía'),
('FK', 'Islas Malvinas'),
('FO', 'Islas Feroe'),
('FJ', 'Fiyi'),
('FI', 'Finlandia'),
('FR', 'Francia'),
('GF', 'Guayana Francesa'),
('PF', 'Polinesia Francesa'),
('TF', 'Territorios Australes Franceses'),
('GA', 'Gabón'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Alemania'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Grecia'),
('GL', 'Groenlandia'),
('GD', 'Granada'),
('GP', 'Guadalupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haití'),
('HM', 'Islas Heard y McDonald'),
('VA', 'Ciudad del Vaticano'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungría'),
('IS', 'Islandia'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Irán'),
('IQ', 'Irak'),
('IE', 'Irlanda'),
('IM', 'Isla de Man'),
('IL', 'Israel'),
('IT', 'Italia'),
('JM', 'Jamaica'),
('JP', 'Japón'),
('JE', 'Jersey'),
('JO', 'Jordania'),
('KZ', 'Kazajstán'),
('KE', 'Kenia'),
('KI', 'Kiribati'),
('KP', 'Corea del Norte'),
('KR', 'Corea del Sur'),
('KW', 'Kuwait'),
('KG', 'Kirguistán'),
('LA', 'Laos'),
('LV', 'Letonia'),
('LB', 'Líbano'),
('LS', 'Lesoto'),
('LR', 'Liberia'),
('LY', 'Libia'),
('LI', 'Liechtenstein'),
('LT', 'Lituania'),
('LU', 'Luxemburgo'),
('MO', 'Macao'),
('MK', 'Macedonia del Norte'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malasia'),
('MV', 'Maldivas'),
('ML', 'Malí'),
('MT', 'Malta'),
('MH', 'Islas Marshall'),
('MQ', 'Martinica'),
('MR', 'Mauritania'),
('MU', 'Mauricio'),
('YT', 'Mayotte'),
('MX', 'México'),
('FM', 'Micronesia'),
('MD', 'Moldavia'),
('MC', 'Mónaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Marruecos'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Países Bajos'),
('NC', 'Nueva Caledonia'),
('NZ', 'Nueva Zelanda'),
('NI', 'Nicaragua'),
('NE', 'Níger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Isla Norfolk'),
('MP', 'Islas Marianas del Norte'),
('NO', 'Noruega'),
('OM', 'Omán'),
('PK', 'Pakistán'),
('PW', 'Palau'),
('PS', 'Palestina'),
('PA', 'Panamá'),
('PG', 'Papúa Nueva Guinea'),
('PY', 'Paraguay'),
('PE', 'Perú'),
('PH', 'Filipinas'),
('PN', 'Pitcairn'),
('PL', 'Polonia'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Catar'),
('RE', 'Reunión'),
('RO', 'Rumania'),
('RU', 'Rusia'),
('RW', 'Ruanda'),
('BL', 'San Bartolomé'),
('SH', 'Santa Elena'),
('KN', 'San Cristóbal y Nieves'),
('LC', 'Santa Lucía'),
('MF', 'San Martín'),
('PM', 'San Pedro y Miquelón'),
('VC', 'San Vicente y las Granadinas'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Santo Tomé y Príncipe'),
('SA', 'Arabia Saudita'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leona'),
('SG', 'Singapur'),
('SX', 'Sint Maarten'),
('SK', 'Eslovaquia'),
('SI', 'Eslovenia'),
('SB', 'Islas Salomón'),
('SO', 'Somalia'),
('ZA', 'Sudáfrica'),
('GS', 'Islas Georgias del Sur y Sandwich del Sur'),
('SS', 'Sudán del Sur'),
('ES', 'España'),
('LK', 'Sri Lanka'),
('SD', 'Sudán'),
('SR', 'Surinam'),
('SJ', 'Svalbard y Jan Mayen'),
('SZ', 'Suazilandia'),
('SE', 'Suecia'),
('CH', 'Suiza'),
('SY', 'Siria'),
('TW', 'Taiwán'),
('TJ', 'Tayikistán'),
('TZ', 'Tanzania'),
('TH', 'Tailandia'),
('TL', 'Timor Oriental'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad y Tobago'),
('TN', 'Túnez'),
('TR', 'Turquía'),
('TM', 'Turkmenistán'),
('TC', 'Islas Turcas y Caicos'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ucrania'),
('AE', 'Emiratos Árabes Unidos'),
('GB', 'Reino Unido'),
('US', 'Estados Unidos'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistán'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('VG', 'Islas Vírgenes Británicas'),
('VI', 'Islas Vírgenes de los Estados Unidos'),
('WF', 'Wallis y Futuna'),
('EH', 'Sahara Occidental'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabue');


